// Auto-generated by scripts/extract-profile.js

export const profile = {
  name: "Ankit Bajpai",
  title: "MarTech Expert | AI Advisory",
  bio: "With over a decade of experience in digital marketing and technology consulting, I specialize in leveraging AI and customer data intelligence to create hyper-personalized experiences that drive business growth. As the Head of Digital Marketing Practice at Nagarro, I lead breakthrough strategies that redefine modern marketing for global brands. Let’s connect and explore how Data Intelligence + Technology + AI can transform your customer engagement.",
  experience: [
  {
    "role": "MarTech Practice Head",
    "company": "",
    "start": "2023",
    "end": "Present",
    "bullets": [
      "Head - Digital Marketing Practice at Nagarro",
      "Strategizing Digital Transformations with Thinking Breakthroughs",
      "Redefining Marketing for Modern Businesses through AI",
      "MarTech Advisory & AI-driven Customer Data Intelligence Expert"

    ]
  },
  {
    "role": "Senior Manager | Senior Tech Consultant",
    "company": "adidas",
    "start": "2022",
    "end": "2023",
    "bullets": [
      "Provide consultation to Brand team on implementation strategies in Consumer Engagement",
      "Oversee platform usage, performance and execution of digitalcommunications at Adidas for Global Markets",
      "Define roadmap for the next generation consumer communications platforms as a technology consultant",
      "Define strategies for digital communication and consumer engagement"
    ]
  }
],
  certifications: [
    {
      title: "Post Graduation Program in Management",
      issuer: "UCLA Anderson",
      url: "https://verified.sertifier.com/en/verify/07018855706328/",
      description: "Management program focused on strategy, leadership, and business fundamentals from UCLA Anderson."
    },
    {
      title: "Generative AI Certified Implementation Expert",
      issuer: "Udemy",
      url: "https://www.udemy.com/certificate/UC-9b16f95a-5eb7-4fef-a322-49465de8b4a0/",
      description: "Hands-on certification covering design and implementation of GenAI solutions and workflows."
    },
    {
      title: "Salesforce Certified Consultant",
      issuer: "Salesforce",
      url: "",
      description: "Consultant-level expertise in Salesforce solutions across implementation and best practices."
    }
  ],
  resumeUrl: "/Ankit_Bajpai_MarTechLeader.pdf",
} as const;
