// Auto-generated by scripts/extract-profile.js

export const profile = {
  name: "Ankit Bajpai",
  title: "Marketing Technologist & Software Engineer",
  bio: "I  am  writing  to  express  my  interest  in  leadership  roles  within  the  Marketing",
  experience: [
  {
    "role": "Marketing Technology Lead",
    "company": "",
    "start": "2022",
    "end": "Present",
    "bullets": [
      "Led CDP strategy and implementation across marketing stack.",
      "Built automation workflows and analytics pipelines.",
      "Drove AI-assisted personalization and lifecycle programs."
    ]
  },
  {
    "role": "Software Engineer",
    "company": "",
    "start": "2016",
    "end": "2022",
    "bullets": [
      "Developed data-driven systems enabling reporting and attribution.",
      "Built services integrating marketing data sources."
    ]
  }
],
  resumeUrl: "/Ankit_Bajpai_MarTechLeader.pdf",
} as const;
